!!python/object/new:config.EasyDict
dictitems:
  base: &id002 !!python/object/new:config.EasyDict
    dictitems:
      gpu_id: &id001
      - '0'
      - '1'
      loss_name: binary_cross_entropy
      opt_name: adam
      scheduler_name: warmup_scheduler
      yaml: 003_seresnext_label_smooth_without_any
    state:
      gpu_id: *id001
      loss_name: binary_cross_entropy
      opt_name: adam
      scheduler_name: warmup_scheduler
      yaml: 003_seresnext_label_smooth_without_any
  data: &id003 !!python/object/new:config.EasyDict
    dictitems:
      crop_width: 512
      dataset_name: without_any_smooth_dataset
      fold: 0
      image_size: 512
      is_multi_channel: false
      is_std: false
      is_train: false
      use_smooth_label: true
      window_aug: true
      window_policy: 2
    state:
      crop_width: 512
      dataset_name: without_any_smooth_dataset
      fold: 0
      image_size: 512
      is_multi_channel: false
      is_std: false
      is_train: false
      use_smooth_label: true
      window_aug: true
      window_policy: 2
  model: &id004 !!python/object/new:config.EasyDict
    dictitems:
      adj_model: false
      branch_head: false
      classes: 5
      is_multi_channel: false
      is_pretrained: true
      is_window: false
      model_name: senet
    state:
      adj_model: false
      branch_head: false
      classes: 5
      is_multi_channel: false
      is_pretrained: true
      is_window: false
      model_name: senet
  save: &id005 !!python/object/new:config.EasyDict
    dictitems:
      description: 512x512 image, seresnext50, binary_cross_entropy, 5class prediction
      save_path: ./intermediate_output/seresnext50_label_smoothing_without_any
    state:
      description: 512x512 image, seresnext50, binary_cross_entropy, 5class prediction
      save_path: ./intermediate_output/seresnext50_label_smoothing_without_any
  test: &id006 !!python/object/new:config.EasyDict
    dictitems:
      batch_size: 32
      is_tta: true
      is_validation: false
    state:
      batch_size: 32
      is_tta: true
      is_validation: false
  train: &id007 !!python/object/new:config.EasyDict
    dictitems:
      accumulation_steps: 1
      batch_size: 16
      epoch: 3
      learning_rate: 1.0e-05
      seed: 7777
      warm_start: true
    state:
      accumulation_steps: 1
      batch_size: 16
      epoch: 3
      learning_rate: 1.0e-05
      seed: 7777
      warm_start: true
state:
  base: *id002
  data: *id003
  model: *id004
  save: *id005
  test: *id006
  train: *id007
