epoch: 30
batch_size: 2048
learning_rate: 0.001
model_names: [
        "densenet_adj_prediction",
        "seresnext50_label_smoothing",
        "seresnext50_label_smoothing_without_any",
        "model_base",
        "model_1",
        "model_2",
        "model_3",
    ]