epoch: 30
batch_size: 2048
learning_rate: 0.001
model_names: [
        "densenet_adj_prediction",
        "seresnext50_label_smoothing",
        "seresnext50_label_smoothing_without_any",
        # "sasaki_se_resnext101_mixup_410_with_imagenet_norm",
        # "sasaki_senet154_customlabels",
        # "model001_se_resnext_stage2",
        # "model002_inceptionv4_stage2",
        # "model003_inception_resnet_v2_stage2",
        # "model004_xception_stage2",
    ]